apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "Waiting for MySQL..."
                sleep 5
              done
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.image | quote }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PORT
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_USER
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: {{ .Values.service.type }}
