apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    tier: database
    app.kubernetes.io/managed-by: Helm
  annotations:
      meta.helm.sh/release-name: nebotaskchart
      meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mysql.name }}
    tier: {{ .Values.mysql.tier }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
        tier: {{ .Values.mysql.tier }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image }}
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
              name: {{ .Values.mysql.name }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: {{ .Values.mysql.mysqlPersistenceStorageName }}
      volumes:
        - name: {{ .Values.mysql.mysqlPersistenceStorageName }}
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.persistentVolumeClaimName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mysql.name }}
    tier: {{ .Values.mysql.tier }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ .Values.mysql.name }}
    tier: {{ .Values.mysql.tier }}
  clusterIP: None
